name: EasyPets
author: Vestri
description: EasyPets
version: 0.6
api-version: 1.15
main: ep.java.EasyPets
permissions:
  ep.admin:
    description: admin
    default: op
commands:
  epgive:
    description: give pet
    usage: /epgive [playername] [petname]