name: EasyPets
author: Vestri
description: EasyPets
version: 0.7
api-version: 1.15
main: ep.java.EasyPets
permissions:
  ep.admin:
    description: admin
    default: op
  ep.changename:
    description: changename
    default: op
  ep.changenamecolor:
    description: changename
    default: op
commands:
  epgive:
    description: give pet
    usage: /epgive <playername> [petname]
  epchangename:
    description: hold pet in the main hand
    usage: /epchangename <name>